name: Sync Files
on:
  push:
    branches:
      - main
      - sync_files
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.SYNC_TEST_TOKEN }}
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.app-token.outputs.token}}
